language: android
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
script: ./gradlew build
deploy:
  - provider: script
    script: scripts/bintrayUpload.sh
    skip_cleanup: true
    on:
      tags: true
